### ISSUE TITLE
Block finalization too slow

### ISSUE THREAD

**Issue by piotrwitek** [make-software/casper-nctl-docker#12]
Default setting of node block finalization is taking several minutes, for testing/development purposes this is not usable experience.

To work around that I need to connect with container and manually change `chainspec` or `node-config` of each node which is really cumbersome.

What are your suggestions @davidatwhiletrue to overcome that issue?  
How can I use my own `chainspec` or  `node-config` for each node when running or reseting the container?

**Comment by davidatwhiletrue** [comment]
Thanks for your feedback @piotrwitek . This would be a good improvement. Let me investigate what can be the best way to override these configurations.

**Comment by piotrwitek** [comment]
@davidatwhiletrue To update the block finalization time to be between 8 - 16 seconds please update the following chainspec:

```
minimum_round_exponent = 13
maximum_round_exponent = 14
```

**Comment by davidatwhiletrue** [comment]
@piotrwitek Default values are 12 - 19. i.e. round_length between ~4s and ~9min.

I've pushed a branch called `custom-chain-config`. It contains a `custom-config` folder with custom `chainspec.toml` using 13 -14. And `config.toml` using `deploy_delay=15sec`.

In my tests I get deploy process time reduced from 1 min to ~20-23 seconds. Round length is ~8secs.

To start the container using this custom configuration, run the following command :

```
docker compose -f .\custom-config\docker-compose-custom-config.yml up mynctl
```

Give it a try and let me know if it solves the original issue.

**Comment by piotrwitek** [comment]
@davidatwhiletrue Yep I was testing it and it works great now! I hope you can merge it ASAP :)
